apiVersion: v1
kind: Service
metadata:
  name: biasguard
  namespace: default
  labels:
    app: biasguard
spec:
  selector:
    app: biasguard
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

