apiVersion: v1
kind: Service
metadata:
  name: trustguard
  namespace: default
  labels:
    app: trustguard
spec:
  selector:
    app: trustguard
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

