apiVersion: v1
kind: ConfigMap
metadata:
  name: tokenguard-config
  namespace: default
data:
  TOKENGUARD_CONFIDENCE_THRESHOLD: "0.7"
  TOKENGUARD_MAX_LENGTH: "800"
  TOKENGUARD_MIN_LENGTH: "200"
  TOKENGUARD_HOST: "0.0.0.0"
  TOKENGUARD_PORT: "8000"
  TOKENGUARD_LOG_LEVEL: "INFO"
  TOKENGUARD_LOG_FORMAT: "json"
  TOKENGUARD_ENABLE_METRICS: "true"
  TOKENGUARD_RATE_LIMIT_REQUESTS: "1000"
  TOKENGUARD_CORS_ORIGINS: "*"