apiVersion: v1
kind: Service
metadata:
  name: codeguardians-gateway
  namespace: default
  labels:
    app: codeguardians-gateway
spec:
  selector:
    app: codeguardians-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

