global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "aiguards-gateway"
    static_configs:
      - targets: ["aiguards-gateway-development:8000"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
