apiVersion: v1
kind: Service
metadata:
  name: healthguard
  namespace: default
  labels:
    app: healthguard
spec:
  selector:
    app: healthguard
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

